INTENTS = {
    "TIME_SERIES": "TIME_SERIES",
    "MINISTRY_SCORE": "MINISTRY_SCORE",
    "MINISTRY_PERFORMANCE":"MINISTRY_PERFORMANCE",
    "POLICY_AREA_SCORE": "POLICY_AREA_SCORE",
    "GOAL_SCORE": "GOAL_SCORE",
    "UNKNOWN": "UNKNOWN",
}