# Generated by Django 4.2.6 on 2025-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='icon',
            field=models.TextField(),
        ),
    ]
