# Generated by Django 4.2.6 on 2025-03-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_apps_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
    ]
