# Generated by Django 4.2.6 on 2025-03-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_rename_apps_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.FileField(upload_to='app/icons/'),
        ),
    ]
