# Generated by Django 4.2.6 on 2025-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_contactus_faq_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
