# Generated by Django 4.2.6 on 2025-02-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocommentlike',
            name='like',
        ),
        migrations.AddField(
            model_name='videocomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
