# Generated by Django 4.2.6 on 2025-02-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_remove_videocommentlike_like_videocomment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='reply',
            new_name='replay',
        ),
    ]
