# Generated by Django 4.2.6 on 2025-03-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_rename_reply_videocomment_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to='Videos.video'),
        ),
    ]
