# Generated by Django 4.2.6 on 2025-03-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0004_alter_videolike_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='Videos.videocomment'),
        ),
    ]
