# Generated by Django 4.2.6 on 2025-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0005_alter_videocommentlike_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video/thubnails/'),
        ),
    ]
