# Generated by Django 4.2.6 on 2025-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='excellence',
            field=models.CharField(blank=True, default='Mr', max_length=100, null=True),
        ),
    ]
