# Generated by Django 4.2.6 on 2025-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinstance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
